//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_1
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид занятости.
    /// </summary>
    // *** Start programmer edit section *** (ВидЗанятости CustomAttributes)

    // *** End programmer edit section *** (ВидЗанятости CustomAttributes)
    public enum ВидЗанятости
    {
        
        // *** Start programmer edit section *** (ВидЗанятости.Занято CustomAttributes)

        // *** End programmer edit section *** (ВидЗанятости.Занято CustomAttributes)
        Занято,
        
        // *** Start programmer edit section *** (ВидЗанятости.Свободно CustomAttributes)

        // *** End programmer edit section *** (ВидЗанятости.Свободно CustomAttributes)
        Свободно,
    }
}
