//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// График.
    /// </summary>
    // *** Start programmer edit section *** (График CustomAttributes)

    // *** End programmer edit section *** (График CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГрафикE", new string[] {
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Сотрудники.Должность as \'Должность\'",
            "Дата as \'Дата\'",
            "Время as \'Время\'",
            "Занятость as \'Занятость\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [MasterViewDefineAttribute("ГрафикE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class График : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private string fВремя;
        
        private IIS.Prilozhenie_1.ВидЗанятости fЗанятость;
        
        private IIS.Prilozhenie_1.Сотрудники fСотрудники;
        
        private IIS.Prilozhenie_1.ГрафикРаботы fГрафикРаботы;
        
        // *** Start programmer edit section *** (График CustomMembers)

        // *** End programmer edit section *** (График CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (График.Время CustomAttributes)

        // *** End programmer edit section *** (График.Время CustomAttributes)
        [StrLen(255)]
        public virtual string Время
        {
            get
            {
                // *** Start programmer edit section *** (График.Время Get start)

                // *** End programmer edit section *** (График.Время Get start)
                string result = this.fВремя;
                // *** Start programmer edit section *** (График.Время Get end)

                // *** End programmer edit section *** (График.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (График.Время Set start)

                // *** End programmer edit section *** (График.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (График.Время Set end)

                // *** End programmer edit section *** (График.Время Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (График.Дата CustomAttributes)

        // *** End programmer edit section *** (График.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (График.Дата Get start)

                // *** End programmer edit section *** (График.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (График.Дата Get end)

                // *** End programmer edit section *** (График.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (График.Дата Set start)

                // *** End programmer edit section *** (График.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (График.Дата Set end)

                // *** End programmer edit section *** (График.Дата Set end)
            }
        }
        
        /// <summary>
        /// Занятость.
        /// </summary>
        // *** Start programmer edit section *** (График.Занятость CustomAttributes)

        // *** End programmer edit section *** (График.Занятость CustomAttributes)
        public virtual IIS.Prilozhenie_1.ВидЗанятости Занятость
        {
            get
            {
                // *** Start programmer edit section *** (График.Занятость Get start)

                // *** End programmer edit section *** (График.Занятость Get start)
                IIS.Prilozhenie_1.ВидЗанятости result = this.fЗанятость;
                // *** Start programmer edit section *** (График.Занятость Get end)

                // *** End programmer edit section *** (График.Занятость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (График.Занятость Set start)

                // *** End programmer edit section *** (График.Занятость Set start)
                this.fЗанятость = value;
                // *** Start programmer edit section *** (График.Занятость Set end)

                // *** End programmer edit section *** (График.Занятость Set end)
            }
        }
        
        /// <summary>
        /// График.
        /// </summary>
        // *** Start programmer edit section *** (График.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (График.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_1.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (График.Сотрудники Get start)

                // *** End programmer edit section *** (График.Сотрудники Get start)
                IIS.Prilozhenie_1.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (График.Сотрудники Get end)

                // *** End programmer edit section *** (График.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (График.Сотрудники Set start)

                // *** End programmer edit section *** (График.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (График.Сотрудники Set end)

                // *** End programmer edit section *** (График.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Prilozhenie_1.ГрафикРаботы.
        /// </summary>
        // *** Start programmer edit section *** (График.ГрафикРаботы CustomAttributes)

        // *** End programmer edit section *** (График.ГрафикРаботы CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ГрафикРаботы"})]
        public virtual IIS.Prilozhenie_1.ГрафикРаботы ГрафикРаботы
        {
            get
            {
                // *** Start programmer edit section *** (График.ГрафикРаботы Get start)

                // *** End programmer edit section *** (График.ГрафикРаботы Get start)
                IIS.Prilozhenie_1.ГрафикРаботы result = this.fГрафикРаботы;
                // *** Start programmer edit section *** (График.ГрафикРаботы Get end)

                // *** End programmer edit section *** (График.ГрафикРаботы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (График.ГрафикРаботы Set start)

                // *** End programmer edit section *** (График.ГрафикРаботы Set start)
                this.fГрафикРаботы = value;
                // *** Start programmer edit section *** (График.ГрафикРаботы Set end)

                // *** End programmer edit section *** (График.ГрафикРаботы Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГрафикE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафикE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафикE", typeof(IIS.Prilozhenie_1.График));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of График.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfГрафик CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfГрафик CustomAttributes)
    public class DetailArrayOfГрафик : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Prilozhenie_1.DetailArrayOfГрафик members)

        // *** End programmer edit section *** (IIS.Prilozhenie_1.DetailArrayOfГрафик members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type График by index.
        /// </summary>
        /// <summary>
        /// Adds object with type График.
        /// </summary>
        public DetailArrayOfГрафик(IIS.Prilozhenie_1.ГрафикРаботы fГрафикРаботы) : 
                base(typeof(График), ((ICSSoft.STORMNET.DataObject)(fГрафикРаботы)))
        {
        }
        
        public IIS.Prilozhenie_1.График this[int index]
        {
            get
            {
                return ((IIS.Prilozhenie_1.График)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Prilozhenie_1.График dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
