//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись клиентов.
    /// </summary>
    // *** Start programmer edit section *** (ЗаписьКлиентов CustomAttributes)

    // *** End programmer edit section *** (ЗаписьКлиентов CustomAttributes)
    [AutoAltered()]
    [Caption("Запись клиентов")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаписьКлиентовE", new string[] {
            "НомерЗаписи as \'Номер записи\'",
            "Клиенты as \'Клиенты\'",
            "Клиенты.ФИОКлиента as \'Ф и о клиента\'",
            "Услуги as \'Услуги\'",
            "Услуги.Наименование as \'Наименование\'",
            "Услуги.Стоимость as \'Стоимость\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Клиенты.ФИОКлиента",
            "Услуги.Наименование",
            "Сотрудники.ФИО"})]
    [MasterViewDefineAttribute("ЗаписьКлиентовE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИОКлиента")]
    [MasterViewDefineAttribute("ЗаписьКлиентовE", "Услуги", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ЗаписьКлиентовE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ЗаписьКлиентовL", new string[] {
            "НомерЗаписи as \'Номер записи\'",
            "Клиенты.ФИОКлиента as \'Ф и о клиента\'",
            "Услуги.Наименование as \'Наименование\'"})]
    public class ЗаписьКлиентов : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЗаписи;
        
        private System.DateTime fДатаЗаписи;
        
        private string fВремя;
        
        private IIS.Prilozhenie_1.Клиенты fКлиенты;
        
        private IIS.Prilozhenie_1.Услуги fУслуги;
        
        private IIS.Prilozhenie_1.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ЗаписьКлиентов CustomMembers)

        // *** End programmer edit section *** (ЗаписьКлиентов CustomMembers)

        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьКлиентов.Время CustomAttributes)

        // *** End programmer edit section *** (ЗаписьКлиентов.Время CustomAttributes)
        [StrLen(255)]
        public virtual string Время
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьКлиентов.Время Get start)

                // *** End programmer edit section *** (ЗаписьКлиентов.Время Get start)
                string result = this.fВремя;
                // *** Start programmer edit section *** (ЗаписьКлиентов.Время Get end)

                // *** End programmer edit section *** (ЗаписьКлиентов.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьКлиентов.Время Set start)

                // *** End programmer edit section *** (ЗаписьКлиентов.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (ЗаписьКлиентов.Время Set end)

                // *** End programmer edit section *** (ЗаписьКлиентов.Время Set end)
            }
        }
        
        /// <summary>
        /// ДатаЗаписи.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьКлиентов.ДатаЗаписи CustomAttributes)

        // *** End programmer edit section *** (ЗаписьКлиентов.ДатаЗаписи CustomAttributes)
        public virtual System.DateTime ДатаЗаписи
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьКлиентов.ДатаЗаписи Get start)

                // *** End programmer edit section *** (ЗаписьКлиентов.ДатаЗаписи Get start)
                System.DateTime result = this.fДатаЗаписи;
                // *** Start programmer edit section *** (ЗаписьКлиентов.ДатаЗаписи Get end)

                // *** End programmer edit section *** (ЗаписьКлиентов.ДатаЗаписи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьКлиентов.ДатаЗаписи Set start)

                // *** End programmer edit section *** (ЗаписьКлиентов.ДатаЗаписи Set start)
                this.fДатаЗаписи = value;
                // *** Start programmer edit section *** (ЗаписьКлиентов.ДатаЗаписи Set end)

                // *** End programmer edit section *** (ЗаписьКлиентов.ДатаЗаписи Set end)
            }
        }
        
        /// <summary>
        /// НомерЗаписи.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьКлиентов.НомерЗаписи CustomAttributes)

        // *** End programmer edit section *** (ЗаписьКлиентов.НомерЗаписи CustomAttributes)
        public virtual int НомерЗаписи
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьКлиентов.НомерЗаписи Get start)

                // *** End programmer edit section *** (ЗаписьКлиентов.НомерЗаписи Get start)
                int result = this.fНомерЗаписи;
                // *** Start programmer edit section *** (ЗаписьКлиентов.НомерЗаписи Get end)

                // *** End programmer edit section *** (ЗаписьКлиентов.НомерЗаписи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьКлиентов.НомерЗаписи Set start)

                // *** End programmer edit section *** (ЗаписьКлиентов.НомерЗаписи Set start)
                this.fНомерЗаписи = value;
                // *** Start programmer edit section *** (ЗаписьКлиентов.НомерЗаписи Set end)

                // *** End programmer edit section *** (ЗаписьКлиентов.НомерЗаписи Set end)
            }
        }
        
        /// <summary>
        /// Запись клиентов.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьКлиентов.Клиенты CustomAttributes)

        // *** End programmer edit section *** (ЗаписьКлиентов.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_1.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьКлиентов.Клиенты Get start)

                // *** End programmer edit section *** (ЗаписьКлиентов.Клиенты Get start)
                IIS.Prilozhenie_1.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (ЗаписьКлиентов.Клиенты Get end)

                // *** End programmer edit section *** (ЗаписьКлиентов.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьКлиентов.Клиенты Set start)

                // *** End programmer edit section *** (ЗаписьКлиентов.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (ЗаписьКлиентов.Клиенты Set end)

                // *** End programmer edit section *** (ЗаписьКлиентов.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Запись клиентов.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьКлиентов.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ЗаписьКлиентов.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_1.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьКлиентов.Сотрудники Get start)

                // *** End programmer edit section *** (ЗаписьКлиентов.Сотрудники Get start)
                IIS.Prilozhenie_1.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ЗаписьКлиентов.Сотрудники Get end)

                // *** End programmer edit section *** (ЗаписьКлиентов.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьКлиентов.Сотрудники Set start)

                // *** End programmer edit section *** (ЗаписьКлиентов.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ЗаписьКлиентов.Сотрудники Set end)

                // *** End programmer edit section *** (ЗаписьКлиентов.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Запись клиентов.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьКлиентов.Услуги CustomAttributes)

        // *** End programmer edit section *** (ЗаписьКлиентов.Услуги CustomAttributes)
        [PropertyStorage(new string[] {
                "Услуги"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_1.Услуги Услуги
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьКлиентов.Услуги Get start)

                // *** End programmer edit section *** (ЗаписьКлиентов.Услуги Get start)
                IIS.Prilozhenie_1.Услуги result = this.fУслуги;
                // *** Start programmer edit section *** (ЗаписьКлиентов.Услуги Get end)

                // *** End programmer edit section *** (ЗаписьКлиентов.Услуги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьКлиентов.Услуги Set start)

                // *** End programmer edit section *** (ЗаписьКлиентов.Услуги Set start)
                this.fУслуги = value;
                // *** Start programmer edit section *** (ЗаписьКлиентов.Услуги Set end)

                // *** End programmer edit section *** (ЗаписьКлиентов.Услуги Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаписьКлиентовE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьКлиентовE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьКлиентовE", typeof(IIS.Prilozhenie_1.ЗаписьКлиентов));
                }
            }
            
            /// <summary>
            /// "ЗаписьКлиентовL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьКлиентовL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьКлиентовL", typeof(IIS.Prilozhenie_1.ЗаписьКлиентов));
                }
            }
        }
    }
}
