//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Клиенты.
    /// </summary>
    // *** Start programmer edit section *** (Клиенты CustomAttributes)

    // *** End programmer edit section *** (Клиенты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлиентыE", new string[] {
            "КодКлиента as \'Код клиента\'",
            "ФИОКлиента as \'Ф и о клиента\'",
            "ДатаРождения as \'Дата рождения\'"})]
    [View("КлиентыL", new string[] {
            "КодКлиента as \'Код клиента\'",
            "ФИОКлиента as \'Ф и о клиента\'",
            "ДатаРождения as \'Дата рождения\'"})]
    public class Клиенты : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодКлиента;
        
        private string fФИОКлиента;
        
        private System.DateTime fДатаРождения;
        
        // *** Start programmer edit section *** (Клиенты CustomMembers)

        // *** End programmer edit section *** (Клиенты CustomMembers)

        
        /// <summary>
        /// ДатаРождения.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ДатаРождения CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ДатаРождения CustomAttributes)
        public virtual System.DateTime ДатаРождения
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ДатаРождения Get start)

                // *** End programmer edit section *** (Клиенты.ДатаРождения Get start)
                System.DateTime result = this.fДатаРождения;
                // *** Start programmer edit section *** (Клиенты.ДатаРождения Get end)

                // *** End programmer edit section *** (Клиенты.ДатаРождения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ДатаРождения Set start)

                // *** End programmer edit section *** (Клиенты.ДатаРождения Set start)
                this.fДатаРождения = value;
                // *** Start programmer edit section *** (Клиенты.ДатаРождения Set end)

                // *** End programmer edit section *** (Клиенты.ДатаРождения Set end)
            }
        }
        
        /// <summary>
        /// КодКлиента.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.КодКлиента CustomAttributes)

        // *** End programmer edit section *** (Клиенты.КодКлиента CustomAttributes)
        public virtual int КодКлиента
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.КодКлиента Get start)

                // *** End programmer edit section *** (Клиенты.КодКлиента Get start)
                int result = this.fКодКлиента;
                // *** Start programmer edit section *** (Клиенты.КодКлиента Get end)

                // *** End programmer edit section *** (Клиенты.КодКлиента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.КодКлиента Set start)

                // *** End programmer edit section *** (Клиенты.КодКлиента Set start)
                this.fКодКлиента = value;
                // *** Start programmer edit section *** (Клиенты.КодКлиента Set end)

                // *** End programmer edit section *** (Клиенты.КодКлиента Set end)
            }
        }
        
        /// <summary>
        /// ФИОКлиента.
        /// </summary>
        // *** Start programmer edit section *** (Клиенты.ФИОКлиента CustomAttributes)

        // *** End programmer edit section *** (Клиенты.ФИОКлиента CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОКлиента
        {
            get
            {
                // *** Start programmer edit section *** (Клиенты.ФИОКлиента Get start)

                // *** End programmer edit section *** (Клиенты.ФИОКлиента Get start)
                string result = this.fФИОКлиента;
                // *** Start programmer edit section *** (Клиенты.ФИОКлиента Get end)

                // *** End programmer edit section *** (Клиенты.ФИОКлиента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Клиенты.ФИОКлиента Set start)

                // *** End programmer edit section *** (Клиенты.ФИОКлиента Set start)
                this.fФИОКлиента = value;
                // *** Start programmer edit section *** (Клиенты.ФИОКлиента Set end)

                // *** End programmer edit section *** (Клиенты.ФИОКлиента Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлиентыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыE", typeof(IIS.Prilozhenie_1.Клиенты));
                }
            }
            
            /// <summary>
            /// "КлиентыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлиентыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлиентыL", typeof(IIS.Prilozhenie_1.Клиенты));
                }
            }
        }
    }
}
